// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
  }
}
